### ISSUE TITLE
Where is mips_16b.v?

### ISSUE THREAD

**Issue by COAOY** [ramaxwell/MIPS-16b#1]
Hi,
I try to synthesis your MIPS core, but I can find mips_16b.v file

**Comment by ramaxwell** [comment]
Hi COAOY,
Apologies, I haven't been active on GIT for a while. I just pulled out an old backup and found the dir with this repo in it and it's not completing the vvp compile. I have some time tomorrow to get it working. Check back with me in a couple of days. BTW this runs a subset of the R3000 instruction set. Once I get it working, I will update the readme to include a list of supported instrs.
Ramaxwell

**Comment by ramaxwell** [comment]
She's ugly but she works. Let me know if you have any problems

**Comment by COAOY** [comment]
Hi,

Thank you for your attention

I will try new version


Thanks
